### ISSUE TITLE
kas-fleetshard should be installed using a bundle

### ISSUE THREAD

**Issue by rareddy** [bf2fc6cc711aee1a0c2a/kas-installer#130]
`kas-fleetshard` is currently installed using the yaml files that are copied over from the `kas-fleetshard` repository, this should be converted to using a bundle. The only bundle currently available is in `managed-tenants` repo. we should also consider a public-facing bundle as a separate effort.

**Comment by machi1990** [comment]
For info, kas-fleet-manager support this as part of the standalone cluster implementation. 
- https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/blob/main/internal/kafka/internal/clusters/standalone_provider.go#L155
- https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/blob/main/internal/kafka/internal/clusters/standalone_provider.go#L74

So if this happens, there could be a lot of installation steps cleanup / removed from kas-installer since this is/'will be' taken care of by the fleet manager.

@daveconde is already using this flow to install fleetshard and strimzi operator from the OLM bundle.
